### ISSUE TITLE
Can You Make A Youtube Tutorial On How To Install It Step By Step Please?

### ISSUE THREAD

**Issue by MrGiveItAway-TPK** [gianmarcoguarnier/JARVIS-ChatGPT#1]

**Comment by gianmarcoguarnier** [comment]
I just tried to install everything from a different (Windows) device. Some problems emerged so I updated the README.md tutorial section accordingly

**Comment by danielenapo** [comment]
Also, a video just showing the software at work would be cool!

**Comment by gianmarcoguarnier** [comment]
A video should come out next week. It will include installation and Demo

**Comment by gianmarcoguarnier** [comment]
Video out! https://youtu.be/AcCG7DOwhG8 
Hope it helps.

**Comment by MrGiveItAway-TPK** [comment]
thank you very much
