### ISSUE TITLE
Simple: typo in VirtualAssitant.py check does not apply custom wakewords

### ISSUE THREAD

**Issue by virtuallyaverage** [gianmarcoguarnier/JARVIS-ChatGPT#3]
In VirtualAssistant.py roughly 104 (I am working on a few things so about that area)

the if check has an extra o:
```# AUDIO 
        if 'awake_with_keyowords' in kwargs:
            self.Keywords = kwargs['awake_with_keywords']
        else:
            self.Keywords = awake_with_keywords```

**Comment by virtuallyaverage** [comment]
I fixed this in mine, but it is still in the main repo

**Comment by virtuallyaverage** [comment]
Thanks for working on this, I was actually starting something similar before I found yours. I am currently working on a possible integration with elevenlabs. So that custom voices could be easily used if someone wanted to, without installing tts

**Comment by gianmarcoguarnier** [comment]
I didn't know Evenlabs. Their voices are actually nice to hear. They might be a solid alternative to IBM's. The  point of tts is to clone jarvis voice in real time, tts results are not that refined but other better alternatives like TorToise takes too much time to generate. In the long run I need to explore other alternatives
